### ISSUE TITLE
Remove package @material-ui/core

### ISSUE THREAD

**Issue by lucemans** [dogehousetv/web#106]

**Comment by TG-Techie** [comment]
it looks like the `useMediaQuery` function, provided by material-ui/core, is used in a few places, do you have a suggested replacement?

import:
https://github.com/dogehousetv/web/blob/b94e852f2d64179f195511c37ea68d4eeba1332a/src/pages/profile.tsx#L1
one of several uses:
https://github.com/dogehousetv/web/blob/b94e852f2d64179f195511c37ea68d4eeba1332a/src/pages/dash.tsx#L37

**Comment by TG-Techie** [comment]
Ah! I think I found the answer... looks like /library/hooks/useMediaQuery might have a replacement.
