### ISSUE TITLE
DogeHouse name/logo

### ISSUE THREAD

**Issue by benawad** [dogehousetv/web#122]
I don't know how serious you guys are about this project, but if you plan to make it a serious thing, I would appreciate it if you would change the name/logo. I'm done working on the voice platform for now, but the DogeHouse name/logo/brand is something I'm going to continue to use.

**Comment by 4nkitd** [comment]
sure. but can we use it while we get our alpha up n running ?

**Comment by benawad** [comment]
> sure. but can we use it while we get our alpha up n running ?

I don't care if you use it in dev, I just would appreciate it if you switched it before launch 👍

**Comment by Pythone** [comment]
Cheemshouse?

**Comment by Pythone** [comment]
What is the next use of the dogehouse name?

**Comment by ghost** [comment]
> What is the next use of the dogehouse name?

Maybe for his upcoming project???

**Comment by Pythone** [comment]
DogeHouse Classic?

**Comment by 4nkitd** [comment]
DevTalk

**Comment by ghost** [comment]
> DevTalk

So it's focused for devs only?

**Comment by Pythone** [comment]
# ***WHAT SHOULD OUR NEW NAME BE?*** 
###### *must be related to a meme*

**Comment by Pythone** [comment]
<del>DogeHome?</del>
*just sounds like a generic knockoff*
<del>Memechat?</del>
*too generic*
DogeCast?
Cheemsland?
Wazobalo?
TalkTime?
CoinTalk?
**MOONLAND**? - ***to the moon***?
meme.social?

**Comment by Pythone** [comment]
WowChat?

**Comment by Pythone** [comment]
ChatWind?

**Comment by lucemans** [comment]
@benawad
